version: 2
shared: &shared
  working_directory: ~/python-ush
  environment:
    - BASH_ENV: ~/.bash_env
  steps:
    - run:
        name: set bash environment
        command: echo 'export PATH="${HOME}/.local/bin:${PATH}"' >> ~/.bash_env

    - checkout

    - run:
        name: make dev-requirements.txt unique for the python version
        command: |
          echo "# $(python --version)" >> dev-requirements.txt
          cat dev-requirements.txt

    - restore_cache:
        keys:
        - dependencies-{{ checksum "dev-requirements.txt" }}
        - dependencies-

    - run:
        name: install dependencies
        command: |
          pip install --user -r dev-requirements.txt

    - save_cache:
        paths: [ ~/.local ]
        key: dependencies-{{ checksum "dev-requirements.txt" }}

    - run:
        name: run tests
        command: |
          pytest --doctest-glob=*.rst

jobs:
  "Python 2.7":
    <<: *shared
    docker: [image: "circleci/python:2.7"]
  "Python 3.4":
    <<: *shared
    docker: [image: "circleci/python:3.4"]
  "Python 3.5":
    <<: *shared
    docker: [image: "circleci/python:3.5"]
  "Python 3.6":
    <<: *shared
    docker: [image: "circleci/python:3.6"]

workflows:
  version: 2
  test:
    jobs: ["Python 2.7", "Python 3.4", "Python 3.5", "Python 3.6"]
